### ISSUE TITLE
User can generate a random Disney character

### ISSUE THREAD

**Issue by Alex-piper** [Alex-piper/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Generate a random Disney Character

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a button that allows users to generate a random Disney character
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/110204706/202040794-01356f4e-4a7e-411a-ad56-25a84fdb4795.png)
![image](https://user-images.githubusercontent.com/110204706/202041059-8187bf68-a29a-41aa-8385-258e136145f7.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Add a div [data-view='character-generator'] to the HTML
- [ ] add a button to the HTML
- [ ] Ensure the layout looks nice on both mobile and desktop screens.
- [ ] listen for the 'click' event on the button and :
     - [ ] Hide the first message
     - [ ] set the image src 
     - [ ] set the Name 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
